<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\NextDrop.Modules.Customers.Application\NextDrop.Modules.Customers.Application.csproj" />
    <ProjectReference Include="..\NextDrop.Modules.Customers.Domain\NextDrop.Modules.Customers.Domain.csproj" />
    <ProjectReference Include="..\..\..\NextDrop.SharedKernel\NextDrop.SharedKernel.csproj" />
    <ProjectReference Include="..\..\..\NextDrop.Infrastructure\NextDrop.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.2" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
