<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <ProjectReference Include="..\NextDrop.SharedKernel\NextDrop.SharedKernel.csproj" />
    <ProjectReference Include="..\Modules\Identity\NextDrop.Modules.Identity.Domain\NextDrop.Modules.Identity.Domain.csproj" />
    <ProjectReference Include="..\Modules\Identity\NextDrop.Modules.Identity.Application\NextDrop.Modules.Identity.Application.csproj" />
    <ProjectReference Include="..\Modules\Identity\NextDrop.Modules.Identity.Infrastructure\NextDrop.Modules.Identity.Infrastructure.csproj" />
    <ProjectReference Include="..\NextDrop.Infrastructure\NextDrop.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Customers\NextDrop.Modules.Customers.Infrastructure\NextDrop.Modules.Customers.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Restaurants\NextDrop.Modules.Restaurants.Infrastructure\NextDrop.Modules.Restaurants.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Catalog\NextDrop.Modules.Catalog.Infrastructure\NextDrop.Modules.Catalog.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Catalog\NextDrop.Modules.Catalog.Application\NextDrop.Modules.Catalog.Application.csproj" />
    <ProjectReference Include="..\Modules\Catalog\NextDrop.Modules.Catalog.Domain\NextDrop.Modules.Catalog.Domain.csproj" />
    <ProjectReference Include="..\Modules\Orders\NextDrop.Modules.Orders.Infrastructure\NextDrop.Modules.Orders.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Orders\NextDrop.Modules.Orders.Application\NextDrop.Modules.Orders.Application.csproj" />
    <ProjectReference Include="..\Modules\Orders\NextDrop.Modules.Orders.Domain\NextDrop.Modules.Orders.Domain.csproj" />
    <ProjectReference Include="..\Modules\Delivery\NextDrop.Modules.Delivery.Infrastructure\NextDrop.Modules.Delivery.Infrastructure.csproj" />
    <ProjectReference Include="..\Modules\Delivery\NextDrop.Modules.Delivery.Application\NextDrop.Modules.Delivery.Application.csproj" />
    <ProjectReference Include="..\Modules\Delivery\NextDrop.Modules.Delivery.Domain\NextDrop.Modules.Delivery.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="9.0.2" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" Version="9.0.2" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.3" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="7.2.0" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

</Project>
