<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NextDrop.Modules.Delivery.Application\NextDrop.Modules.Delivery.Application.csproj" />
    <ProjectReference Include="..\NextDrop.Modules.Delivery.Domain\NextDrop.Modules.Delivery.Domain.csproj" />
    <ProjectReference Include="..\..\..\NextDrop.Infrastructure\NextDrop.Infrastructure.csproj" />
    <ProjectReference Include="..\..\..\NextDrop.SharedKernel\NextDrop.SharedKernel.csproj" />
  </ItemGroup>

</Project>
